//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Transaction struct {
	WalletID      int32     `sql:"primary_key"`
	TransactionID uuid.UUID `sql:"primary_key"`
	UpdatedAt     time.Time
	CreatedAt     time.Time
}
