//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Wallet struct {
	ID        int32 `sql:"primary_key"`
	Account   uuid.UUID
	Amount    int32
	Currency  string
	UpdatedAt time.Time
	CreatedAt time.Time
}
